**FUNCTION ChkTxn19
PARAMETERS  C_CLCODE, N_TAG
LOCAL  OMED AS OBJECT,   lnCurArea AS String, llTXN19
lnCurArea=ALIAS()
_SCREEN.MOUSEPOINTER=11
PRIVATE OMED AS OBJECT
OMED=CREATEOBJECT("generic.medgeneric")
	SELECT 0

	llTXN19=.F.	
	OMED.CLOSEALIAS( "Hastxn19")
	C_SQL =" SELECT  [dbo].[GetTxn19Count]('" +   FIXQUOTE(C_CLCODE) + "','" + STR(N_TAG) + "')"
	L_OK =OMED.SQLEXECUTE(C_SQL, "Hastxn19")

	IF USED ("Hastxn19")
		llTXN19=		NVL(HASTXN19.EXP,.F.)
	ENDIF
	
	_SCREEN.MOUSEPOINTER=0
	RELEASE OMED
	
	RETURN llTXN19