* display RT logo

_SCREEN.FONTBOLD = .T.
_SCREEN.FONTITALIC = .T.
_SCREEN.FONTNAME="Arial"
_SCREEN.FORECOLOR=0
_SCREEN.FONTSIZE = 18
_SCREEN.PRINT(" RECORDTRAK ", 40, 30)
_SCREEN.FORECOLOR=128
_SCREEN.LINE(61,61, 600,61)
_SCREEN.PRINT ("")
_SCREEN.FONTSIZE = 10
_SCREEN.PRINT ("The Track Record of Success", 90,68)
_SCREEN.PRINT ("")
_SCREEN.FORECOLOR=0
_SCREEN.FONTITALIC = .F.
_SCREEN.FONTSIZE = 16
_SCREEN.PRINT ("Welcome to the Record Tracking System II.", 140,165)
_SCREEN.FONTBOLD = .F.

