**********************************	
PARAMETERS c_action
LOCAL ncurarea
ncurarea=SELECT()

IF c_action="SETDEFAULT"
	*// store original session settings before print
	WAIT WINDOW "Saving session settings" NOWAIT NOCLEAR 
	CREATE CURSOR vfpsettings ;
		(cANSI c(10),cauTOSAVE c(10),cBELLOFF c(10),cBLINK c(10),cBRSTATUS c(10),cCARRY c(10),cCENTURY c(10),cCLEAR  c(10) ;
		,cCLOCK c(10),cCONFIRM c(10),cCONSOLE c(10),cCURSOR c(10),cDEBUG c(10),cDECIMAL INTEGER,cDELETE c(10),cDELIM c(10),cDEVE c(10),cDEVI c(10),cDOHI c(10);
		,cECHO c(10),cESCAPE c(10),cEXACT c(10),cFIELD c(10),cFIXED c(10),cFULLP c(10),cHEAD c(10),cHOURS INTEGER,cKEYCOMP c(10);
		,c_LOCK c(10),cMARK c(10),cMARGIN INTEGER,cMEMO INTEGER,cMOUSE c(10),cMULTI c(10),cNEAR c(10),cNOTI c(10),cOPTI c(10),cPALETTE c(10),cPOINT c(10),cPRINT c(10);
		,cPRINTTO c(10),cPROCE c(250),cREFRE INTEGER,cREPRO INTEGER,cSAFE c(10),cSCOR c(10),cSEPA c(10),cSHADOW c(10),cSTICKY c(10),cTALK c(10);
		,cTYPEA INTEGER,cUDFPA c(10),cUNIQUE c(10),cVIEW c(10);
		,cBELL c(10),cEXCLUS c(10),cDATE c(10),cSTATUSBAR c(10),cCLOCKSTATUS c(10);
		)


   LOCAL cANSI,mauTOSAVE,mBELLOFF,mBLINK,mBRSTATUS,mCARRY,mCENTURY,mCLEAR ;
		,mCLOCK,mCONFIRM,mCONSOLE,mCURSOR,mDEBUG,mDECIMAL,mDELETE,mDELIM,mDEVE,mDEVI,mDOHI;
		,mECHO,mESCAPE,mEXACT,mFIELD,mFIXED,mFULLP,mHEAD,mHOURS,mKEYCOMP;
		,m_LOCK,mMARK,mMARGIN,mMEMO,mMOUSE,mMULTI,mNEAR,mNOTI,mOPTI,mPALETTE,mPOINT,mPRINT;
		,mPRINTTO,mPROCE,mREFRE,mREPRO,mSAFE,mSCOR,mSEPA,mSHADOW,mSTICKY,mTALK;
		,mTYPEA,mUDFPA,mUNIQUE,mVIEW;
		,mBELL,mEXCLUS,mDATE,mSTATUSBAR,mCLOCKSTATUS;


	mANSI=SET('ANSI')
	mauTOSAVE=SET('AUTOSAVE')
	mBELLOFF=SET('BELL')
	mBLINK=SET('BLINK')
	mBRSTATUS=SET('BRSTATUS')
	mCARRY=SET('CARRY')
	mCENTURY=SET('CENTURY')
	mCLEAR=SET('CLEAR')
	mCLOCK=SET('CLOCK')
	mCONFIRM=SET('CONFIRM')
	mCONSOLE=SET('CONSOLE')
	mCURSOR=SET('CURSOR')
	mDEBUG=SET('DEBUG')
	mDECIMAL=SET('DECIMAL')
	mDELETE=SET('DELETE')
	mDELIM=SET('DELIM')
	mDEVE=SET('DEVE')
	mDEVI=SET('DEVI')
	mDOHI=SET('DOHI')
	mECHO=SET('ECHO')
	mESCAPE=SET('ESCAPE')
	mEXACT=SET('EXACT')
	mFIELD=SET('FIELD')
	mFIXED=SET('FIXED')
	mFULLP=SET('FULLP')
	mHEAD=SET('HEAD')
	mHOURS=SET('HOURS')
	mKEYCOMP=SET('KEYCOMP')
	m_LOCK=SET('LOCK')
	mMARK=SET('MARK')
	mMARGIN=SET('MARGIN')
	mMEMO=SET('MEMO')
	mMOUSE=SET('MOUSE')
	mMULTI=SET('MULTI')
	mNEAR=SET('NEAR')
	mNOTI=SET('NOTI')
	mOPTI=SET('OPTI')
	mPALETTE=SET('PALETTE')
	mPOINT=SET('POINT')
	mPRINT=SET('PRINT')
	mPRINTTO=SET('PRINT TO')
	mPROCE=SET('PROCE')
	mREFRE=SET('REFRE')
	mREPRO=SET('REPRO')
	mSAFE=SET('SAFE')
	mSCOR=SET('SCOR')
	mSEPA=SET('SEPA')
	mSHADOW=SET('SHADOW')
	mSTICKY=SET('STICKY')
	mTALK=SET('TALK')
	mTYPEA=SET('TYPEA')
	mUDFPA=SET('UDFPA')
	mUNIQUE=SET('UNIQUE')
	mVIEW=SET('view')
	mBELL=SET('bell')
	mCONFIRM=SET('confirm')
	mEXCLUS=SET('EXCLUS')
	mDATE=SET('date')
	mSTATUSBAR=SET('STATUS BAR')
	mCLOCKSTATUS=SET('CLOCK STATUS')
	mTALK=SET('talk')
	mECHO=SET('echo')
	mSAFE=SET('safe')


	INSERT INTO vfpsettings VALUES ;
		(mANSI,mauTOSAVE,mBELLOFF,mBLINK,mBRSTATUS,mCARRY,mCENTURY,mCLEAR ;
		,mCLOCK,mCONFIRM,mCONSOLE,mCURSOR,mDEBUG,mDECIMAL,mDELETE,mDELIM,mDEVE,mDEVI,mDOHI;
		,mECHO,mESCAPE,mEXACT,mFIELD,mFIXED,mFULLP,mHEAD,mHOURS,mKEYCOMP;
		,m_LOCK,mMARK,mMARGIN,mMEMO,mMOUSE,mMULTI,mNEAR,mNOTI,mOPTI,mPALETTE,mPOINT,mPRINT;
		,mPRINTTO,mPROCE,mREFRE,mREPRO,mSAFE,mSCOR,mSEPA,mSHADOW,mSTICKY,mTALK;
		,mTYPEA,mUDFPA,mUNIQUE,mVIEW;
		,mBELL,mEXCLUS,mDATE,mSTATUSBAR,mCLOCKSTATUS)



	SET ANSI ON
	SET AUTOSAVE ON
	SET BELL OFF
	SET BELL TO 400,2
	SET BLINK ON
	SET BRSTATUS OFF
	SET CARRY OFF
	SET CENTURY ON
	SET CLEAR OFF
	SET CLOCK OFF
	SET CONFIRM OFF
	SET CONSOLE ON
	SET CURSOR ON

	SET DEBUG OFF
	SET DECIMAL TO 16
	SET DELETE ON
	SET DELIM OFF
	SET DEVELOPMENT ON
	SET DEVI TO SCREEN
	SET DOHI OFF
	SET ECHO OFF
	SET ESCAPE OFF
	SET EXACT OFF
	SET EXCLUS OFF
	SET FIELD TO
	SET FIXED OFF
	SET FORMAT TO
	SET FULLP ON
	SET HEAD OFF
	SET HELP OFF
	SET HOURS TO 24
	SET KEYCOMP TO DOS
	SET LOCK OFF
	*SET MARK TO "-"
	SET MARGIN TO 0
	SET MEMO TO 72
	SET MOUSE ON
	SET MULTI ON
	SET NEAR OFF
	SET NOTI OFF
	SET OPTI ON
	SET PALETTE ON
*	SET POINT TO "'"
	SET PRINT OFF
	SET PRINT TO
*	SET PROCE TO
	SET REFRE TO 1
	SET REPRO TO 0
	SET SAFE OFF
	SET SCOR OFF
*	SET SEPA TO "."
	SET SHADOW ON
	SET STAT OFF
	SET STEP OFF
	SET STICKY ON
	SET TALK OFF
	*SET TEXTM OFF
	SET TYPEA TO 50
	SET UDFPA TO VALUE
	SET UNIQUE OFF
	SET VIEW OFF
*
	SET BELL ON
	SET CONFIRM OFF
	SET STATUS BAR OFF
	SET CLOCK STATUS

	WAIT CLEAR 
ELSE
	IF NOT USED('vfpsettings')
		gfmessage("Stored session settings not found after print.")
		SELECT (ncurarea)
		RETURN
	ENDIF 			
	*// restore original settings
	SELECT vfpsettings
	GO top
	SCATTER MEMVAR
	SELECT 0

	SET ANSI &cANSI.
	SET AUTOSAVE &cauTOSAVE.
	SET BELL &cBELLOFF.
	SET BLINK &cBLINK.
	SET BRSTATUS &cBRSTATUS.
	SET CARRY &cCARRY.
	SET CENTURY &cCENTURY.
	SET CLEAR &cCLEAR.
	SET CLOCK &cCLOCK.
	SET CONFIRM &cCONFIRM.
	SET CONSOLE &cCONSOLE.
	SET CURSOR &cCURSOR.
	SET DEBUG &cDEBUG.
	SET DECIMALS TO &cDECIMAL.
	SET DELETED &cDELETE.
	SET DELIM  &cDELIM.
	SET DEVELOPMENT  &cDEVE.
	SET DEVICE TO  &cDEVI.
	SET DOHI &cDOHI.
	SET ECHO &cECHO.
	SET ESCAPE &cESCAPE.
	SET EXACT &cEXACT.
	SET FIELDS &cFIELD.
	SET FIXED &cFIXED.
	SET FULLP &cFULLP.
	SET HEAD &cHEAD.
	SET HOURS TO &cHOURS.
	SET KEYCOMP TO &cKEYCOMP.
	SET LOCK &c_LOCK.
	*SET MARK TO "&cMARK."
	SET MARGIN TO (vfpsettings.cMARGIN)
	SET MEMO TO IIF(NVL(vfpsettings.cMEMO,0)<8,51,cMEMO)
	SET MOUSE &cMOUSE.
	SET MULTI &cMULTI.
	SET NEAR &cNEAR.
	SET NOTI &cNOTI.
	SET OPTI &cOPTI.
	SET PALETTE &cPALETTE.
*	SET POINT TO "&cPOINT."
	SET PRINT &cPRINT.
	SET PRINTER TO &cPRINTTO.
	IF NOT EMPTY(cPROCE)
*		SET PROCE TO &cPROCE.
	ENDIF
	SET REFRE TO (vfpsettings.cREFRE)
	SET REPRO TO (vfpsettings.cREPRO)
	SET SAFE &cSAFE.
	SET SCOR &cSCOR.
*	SET SEPA TO &cSEPA.
	SET SHADOW &cSHADOW.
	SET STICKY &cSTICKY.
	SET TALK &cTALK.
	SET TYPEA TO (vfpsettings.cTYPEA)
	SET UDFPARMS TO  &cUDFPA.
	SET UNIQUE &cUNIQUE.
	IF NOT EMPTY(vfpsettings.cVIEW)
		SET VIEW &cVIEW.
	ENDIF
	SET BELL &cBELL.
	SET CONFIRM &cCONFIRM.
	SET EXCLUS &cEXCLUS.
	SET STATUS BAR &cSTATUSBAR.
	SET CLOCK STATUS &cCLOCKSTATUS.
*SET MESSAGE TO &cMESSAGETO.
	SET TALK &cTALK.
	SET ECHO &cECHO.
	SET SAFE &cSAFE.

	USE IN vfpsettings

ENDIF
SELECT (ncurarea)